### ISSUE TITLE
Metaticket - TODO list for initial release

### ISSUE THREAD

**Issue by ewlarson** [bplmaps/blacklight-allmaps#2]
TODO list for initial release...

- [x] LICENSE file
- [x] LICENSE: Add Name of copyright owner
- [x] Rails Engine scaffold
- [x] Standard.rb / Linter
- [x] Solr: via SolrWrapper or Lando?
- [x] EngineCart
- [x] Test fixtures: GBL > Allmaps georeferenced
- [x] Test fixtures: GBL > Allmaps NOT georeferenced
- [x] Test fixtures: BL (Marc) > Allmaps georeferenced
- [x] Test fixtures: BL (Marc) > Allmaps NOT georeferenced
- [x] GitHub Actions / CI
- [x] Dependabot
- [x] RSpec test suite
- [x] Show page / Toolbar button(s)
- [x] RDBMS: SidecarAllmaps table
- [x] Rake tasks for indexing / maintenance
- [x] Open source / Public repo
- [x] Install script(s) accept args for BL vs. GBL
- [x] Install script(s) accept args for Bootstrap v4 and Bootstrap v5
- [x] Test matrix: Ruby v3.2, v3.3
- [ ] Test matrix: Rails v7.0, v.71
- [ ] a11y: Accessibility review
- [ ] Test matrix: Blacklight v7 and v8
- [x] Test matrix: GeoBlacklight v4
- [x] Index page / Georeferenced facet
- [x] i18n: locales en file, others?

**Comment by ewlarson** [comment]
Closing as no longer relevant.
